### ISSUE TITLE
Feature: Use Secrests to store the API Key

### ISSUE THREAD

**Issue by biovolt** [w1tw0lf/homeassitant#1]
Thank you for your work!!!!!!!
It will really help

You can store the api key and area in homeassistant's secrets.yaml and reference it via !secret. 

e.g. 

```
    headers:
      Token: !secret.espapikey 
    params:
      id: !secret.espareaid
```

https://www.home-assistant.io/docs/configuration/secrets/
